name: Basel Monorepo Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-build
      - run: bazel build //...
      - run: bazel run :cdk -- synth
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-test
      - run: bazel test //...
