name: Basel Monorepo Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
  BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-build-${{ env.HEAD_SHA }}
          restore-keys: |
            bazel-build-${{ env.BASE_SHA }}
            bazel-build-

      - run: bazel build //...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-build-${{ env.HEAD_SHA }}
          restore-keys: |
            bazel-build-${{ env.BASE_SHA }}
            bazel-build-

      - run: bazel test //...

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-build-${{ env.HEAD_SHA }}
          restore-keys: |
            bazel-build-${{ env.BASE_SHA }}
            bazel-build-

      - run: bazel build //... --sandbox_debug --config=release

      - name: publish cdk-core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: cd bazel-bin/node_modules/@lonnblad/bacel-poc.cdk-core && pnpm publish --dry-run --no-git-checks
