name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-build-${GITHUB_SHA}
          restore-keys: |
            bazel-build-

      - run: bazel build //...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-test-${GITHUB_SHA}
          restore-keys: |
            bazel-test-

      - run: bazel test //...

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-build-${GITHUB_SHA}
          restore-keys: |
            bazel-build-

      - run: bazel build //... --sandbox_debug --config=release

      - uses: pnpm/action-setup@v2
        with:
          version: 7.13

      - name: publish cdk-core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: cd bazel-bin/node_modules/@lonnblad/bacel-poc.cdk-core && pnpm publish --dry-run --no-git-checks
